import './globals.css'
import type { Metadata } from 'next'
import { Inter, Kanit } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const kanit = Kanit({
  subsets: ['latin'],
  display: 'swap',
  weight: '500'
});

export const metadata: Metadata = {
  title: 'Weather app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>{children}</body>
    </html>
  )
}
